server:
  port: 8090
spring:
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://192.168.62.201:5236/DAMENG?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: SYSDBA
    password: admin123456
  # 配置时间返回格式与时区问题
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 50MB       # 上传单个文件最大值
      max-request-size: 100MB   # 上传单次总文件最大值
# 配置mybatis mapper文件路径
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  # 配置mybatis懒加载
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
# 日志配置
logging:
  config: classpath:logback-spring.xml
# jwt加密信息
jwt:
  jwtKey: spring-boot-jwt-key~#^
# 配置文件上传存放路径
file:
  path: D:/file/upload/
# 拦截器不拦截的请求
interceptor:
  excludePathPatterns: /login, /swagger-resources/**, /webjars/**, /v2/**, /swagger-ui.html/**
# casbin配置
casbin:
  driver: ${spring.datasource.driver-class-name}
  url: ${spring.datasource.url}
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}
  dbSpecified: true
  model: classpath:casbin/rbac_model.conf