# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
  port: 8080
spring:
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.100.2.1:3306/template?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin123
  # 配置时间返回格式与时区问题
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 50MB       # 上传单个文件最大值
      max-request-size: 100MB   # 上传单次总文件最大值
# 配置mybatis mapper文件路径
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
# 日志配置
logging:
  config: classpath:logback-spring.xml
# jwt加密信息
some:
  work:
    jwtMethod: auth
    jwtKey: spring-boot-jwt-key~#^
# 配置文件上传存放路径
file:
  path: D:/file/upload/
# 拦截器不拦截的请求
interceptor:
  excludePathPatterns: /login, /swagger-resources/**, /webjars/**, /v2/**, /swagger-ui.html/**